package com.example.librarymanager.constant;

public enum RoleConstant {
    ROLE_MANAGE_AUTHOR,
    ROLE_MANAGE_BOOK,
    ROLE_MANAGE_BOOK_DEFINITION,
    ROLE_MANAGE_BOOK_SET,
    ROLE_MANAGE_CATEGORY,
    ROLE_MANAGE_CATEGORY_GROUP,
    ROLE_MANAGE_CLASSIFICATION_SYMBOL,
    ROLE_MANAGE_IMPORT_RECEIPT,
    ROLE_MANAGE_LOG,
    ROLE_MANAGE_NEWS_ARTICLE,
    ROLE_MANAGE_PUBLISHER,
    ROLE_MANAGE_ROLE,
    ROLE_MANAGE_USER,
    ROLE_READER
}
